### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by oppianmatt** [tipsi/pytest-tipsi-django#7]
after adding it to requirements pytest now gives an error:

```
sut_1                  | Launching py.test with arguments /app/xxx/signup/tests/test_views.py in /opt/project
sut_1                  | 
sut_1                  | Traceback (most recent call last):
sut_1                  |   File "/opt/.pycharm_helpers/pycharm/_jb_pytest_runner.py", line 31, in <module>
sut_1                  |     pytest.main(args, plugins_to_load)
sut_1                  |   File "/usr/local/lib/python2.7/site-packages/_pytest/config.py", line 52, in main
sut_1                  |     config = _prepareconfig(args, plugins)
sut_1                  |   File "/usr/local/lib/python2.7/site-packages/_pytest/config.py", line 163, in _prepareconfig
sut_1                  |     pluginmanager=pluginmanager, args=args)
sut_1                  |   File "/usr/local/lib/python2.7/site-packages/pluggy/__init__.py", line 617, in __call__
sut_1                  |     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
sut_1                  |   File "/usr/local/lib/python2.7/site-packages/pluggy/__init__.py", line 222, in _hookexec
sut_1                  |     return self._inner_hookexec(hook, methods, kwargs)
sut_1                  |   File "/usr/local/lib/python2.7/site-packages/pluggy/__init__.py", line 216, in <lambda>
sut_1                  |     firstresult=hook.spec_opts.get('firstresult'),
sut_1                  |   File "/usr/local/lib/python2.7/site-packages/pluggy/callers.py", line 196, in _multicall
sut_1                  |     gen.send(outcome)
sut_1                  |   File "/usr/local/lib/python2.7/site-packages/_pytest/helpconfig.py", line 68, in pytest_cmdline_parse
sut_1                  |     config = outcome.get_result()
sut_1                  |   File "/usr/local/lib/python2.7/site-packages/pluggy/callers.py", line 77, in get_result
sut_1                  |     _reraise(*ex)  # noqa
sut_1                  |   File "/usr/local/lib/python2.7/site-packages/pluggy/callers.py", line 180, in _multicall
sut_1                  |     res = hook_impl.function(*args)
sut_1                  |   File "/usr/local/lib/python2.7/site-packages/_pytest/config.py", line 941, in pytest_cmdline_parse
sut_1                  |     self.parse(args)
sut_1                  |   File "/usr/local/lib/python2.7/site-packages/_pytest/config.py", line 1091, in parse
sut_1                  |     self._preparse(args, addopts=addopts)
sut_1                  |   File "/usr/local/lib/python2.7/site-packages/_pytest/config.py", line 1053, in _preparse
sut_1                  |     self.pluginmanager.load_setuptools_entrypoints('pytest11')
sut_1                  |   File "/usr/local/lib/python2.7/site-packages/pluggy/__init__.py", line 397, in load_setuptools_entrypoints
sut_1                  |     plugin = ep.load()
sut_1                  |   File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2318, in load
sut_1                  |     return self.resolve()
sut_1                  |   File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in resolve
sut_1                  |     module = __import__(self.module_name, fromlist=['__name__'], level=0)
sut_1                  |   File "/usr/local/lib/python2.7/site-packages/pytest_tipsi_testing/plugin.py", line 12
sut_1                  |     def _inner(*args, level=1, **kwargs):
sut_1                  |                           ^
sut_1                  | SyntaxError: invalid syntax
xxx_sut_1 exited with code 1
```

**Comment by cybergrind** [comment]
this library doesn't support python2
